/**
* Jikan
* Jikan
*
* The version of the OpenAPI document: 1.3.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package services.jikanAPI

import services.jikanAPI.models.ProductList
import services.jikanAPI.infrastructure.*

class SearchApi {

    private val apiService: ApiConnector = ApiService()
//    private val apiService: ApiConnector = ApiStub()

    suspend fun getAnime(q: String, page: Int, callback: (ProductList) -> Unit) {

        val query = "q=$q"
        val pageStr = "page=$page"

        val path = "v3/search/anime?" + query + "&" + pageStr
        apiService.getData(path, ProductList.serializer(), callback)
    }

    suspend fun getManga(q: String, page: Int, callback: (ProductList) -> Unit) {

        val query = "q=$q"
        val pageStr = "page=$page"

        val path = "v3/search/manga?" + query + "&" + pageStr
        apiService.getData(path, ProductList.serializer(), callback)
    }
}
