/**
* Jikan
* Jikan
*
* The version of the OpenAPI document: 1.3.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package services.jikanAPI.models

enum class ErrorType {
    NETWORK, AUTH, TECH, OTHER, NOTFOUND, BADANSWER
}

/**
 *
 * @param code
 * @param errorType
 * @param message
 * @param type
 */
data class ErrorModel (
    var code: Int = 0,
    var errorType: String = "",
    var message: String = "",

    var type: ErrorType = ErrorType.OTHER
)

