/**
* Jikan
* Jikan
*
* The version of the OpenAPI document: 1.3.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package services.jikanAPI.models

import kotlinx.serialization.*

/**
 * 
 * @param message 
 * @param code 
 */
@Serializable
data class ErrorModel (
    @SerialName(value = "message") @Required val message: String,
    @SerialName(value = "code") @Required val code: Int
)

