/**
* Jikan
* Jikan
*
* The version of the OpenAPI document: 1.3.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package services.jikanAPI.models

import kotlinx.serialization.*

/**
 * 
 * @param malId 
 * @param imageUrl 
 * @param title 
 * @param synopsis 
 * @param type 
 * @param members 
 * @param score 
 */
@Serializable
data class Product (
    @SerialName(value = "mal_id") val malId: Int,
    @SerialName(value = "image_url") val imageUrl: String,
    @SerialName(value = "title") val title: String,
    @SerialName(value = "synopsis") val synopsis: String,
    @SerialName(value = "type") val type: String,
    @SerialName(value = "members") val members: Int,
    @SerialName(value = "score") val score: Double
)

