openapi: 3.0.1
info:
  title: Jikan
  description: 'Jikan'
  version: 1.3.1
externalDocs:
  description: API Root
  url: https://api.jikan.moe/v3/
servers:
- url: https://api.jikan.moe/v3/
paths:
  /search/anime:
    get:
      tags:
      - search
      summary: Get Anime
      operationId: getAnime
      parameters:
        - name: q
          in: query
          description: Query
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Paging
          required: true
          schema:
            type: integer  
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /search/manga:
    get:
      tags:
      - search
      summary: Get Manga
      operationId: getManga
      parameters:
        - name: q
          in: query
          description: Query
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Paging
          required: true
          schema:
            type: integer  
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ProductList:
      type: object
      required:
      - last_page
      - image_url
      properties:
        last_page:
          type: integer
        results:
          type: array
          items: 
            $ref: "#/components/schemas/Product"
    Product:
      type: object
      required:
      - mal_id
      - image_url
      - title
      - synopsis
      - type
      - members
      - score
      properties:
        mal_id:
          type: integer
        image_url:
          type: string
        title:
          type: string
        synopsis:
          type: string
        type:
          type: string
        members:
          type: integer
        score:
          type: number
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600