//
// Anime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Anime: Codable, Identifiable, Hashable {
    
    public var id: Int {
        malId ?? UUID().hashValue
    }
    
    public var imgURL: URL? {
        URL(string: imageUrl ?? "")
    }
    
    public var malId: Int?
    public var imageUrl: String?
    public var title: String?
    public var synopsis: String?
    public var episodes: Int?
    public var score: Double?

    public init(malId: Int?, imageUrl: String?, title: String?, synopsis: String?, episodes: Int?, score: Double?) {
        self.malId = malId
        self.imageUrl = imageUrl
        self.title = title
        self.synopsis = synopsis
        self.episodes = episodes
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case malId = "mal_id"
        case imageUrl = "image_url"
        case title
        case synopsis
        case episodes
        case score
    }

}
